name: Bug report
description: File a bug/defect
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps/code to reproduce the issue
      placeholder: |
        1. …
        2. …
        3. …
  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      render: shell
  - type: input
    id: version
    attributes:
      label: pyalexs3 version
      placeholder: 0.1.0
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: 3.12
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14 / Ubuntu 22.04 / Windows 11
